---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: sock-shop
  name: front-end
  namespace: sock-shop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: front-end
status:
  loadBalancer: {}
